# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_redm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1110, 887)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.redmensionar = QtWidgets.QPushButton(self.centralwidget)
        self.redmensionar.setObjectName("redmensionar")
        self.gridLayout.addWidget(self.redmensionar, 3, 4, 1, 1)
        self.input_altura = QtWidgets.QLineEdit(self.centralwidget)
        self.input_altura.setObjectName("input_altura")
        self.gridLayout.addWidget(self.input_altura, 3, 3, 1, 1)
        self.largura = QtWidgets.QLabel(self.centralwidget)
        self.largura.setObjectName("largura")
        self.gridLayout.addWidget(self.largura, 3, 0, 1, 1)
        self.input_largura = QtWidgets.QLineEdit(self.centralwidget)
        self.input_largura.setObjectName("input_largura")
        self.gridLayout.addWidget(self.input_largura, 3, 1, 1, 1)
        self.altura = QtWidgets.QLabel(self.centralwidget)
        self.altura.setObjectName("altura")
        self.gridLayout.addWidget(self.altura, 3, 2, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1090, 780))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.image = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.image.setObjectName("image")
        self.gridLayout_2.addWidget(self.image, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 5)
        self.input = QtWidgets.QPushButton(self.centralwidget)
        self.input.setObjectName("input")
        self.gridLayout.addWidget(self.input, 1, 4, 1, 1)
        self.salvar = QtWidgets.QPushButton(self.centralwidget)
        self.salvar.setObjectName("salvar")
        self.gridLayout.addWidget(self.salvar, 4, 4, 1, 1)
        self.input_path = QtWidgets.QLineEdit(self.centralwidget)
        self.input_path.setObjectName("input_path")
        self.gridLayout.addWidget(self.input_path, 1, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Redimensionar imagem"))
        self.redmensionar.setText(_translate("MainWindow", "Redmensionar"))
        self.largura.setText(_translate("MainWindow", "Largura"))
        self.altura.setText(_translate("MainWindow", "Altura"))
        self.image.setText(_translate("MainWindow", "TextLabel"))
        self.input.setText(_translate("MainWindow", "Escolher Arquivo"))
        self.salvar.setText(_translate("MainWindow", "Salvar"))
